#!/bin/bash
# This script is heavily adapted from Thoughtbot's awesome laptop setup script
# Source: https://github.com/thoughtbot/laptop/blob/master/mac

HOMEBREW_PREFIX="/usr/local"
ASDF_HOME="$HOME/.asdf"

fancy_echo() {
  local fmt="$1"; shift
  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

add_or_install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
   else
     asdf plugin-update "$name"
  fi
}

install_asdf_language() {
  local language="$1"
  local version
  version="$(asdf list-all "$language" | grep -v "[a-z]" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

fancy_echo "Starting up..."

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ -d "$HOMEBREW_PREFIX" ]; then 
  if ! [ -r "$HOMEBREW_PREFIX" ]; then 
    sudo chown - R "$LOGNAME:admin" /usr/local
  fi 
else 
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi 

if ! command -v brew >/dev/null; then 
  fancy_echo '🍺 Installing brew...'
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
  
fi

if brew list | grep -Fq brew-cask; then 
  fancy_echo "✂️  Uninstalling old homebrew cask ..."
  brew uninstall --force brew-cask 
fi

fancy_echo "🍻 Updating homebrew formulae..."
brew update --force  # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=./Brewfile

fancy_echo "🍻 Your brews and casks have been successfully installed"

fancy_echo "Update heroku binary ..."
brew unlink heroku
brew link --force heroku

fancy_echo "🍺 Brew was successfully installed ✅"


fancy_echo "🐠 Configuring fish as default shell..."
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish
fancy_echo "🐠 fish set as default shell"

fancy_echo 'Setting up asdf...'

# # shellcheck disable=SC1090
# source "$HOME/.asdf/asdf.sh"
add_or_install_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
add_or_install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

fancy_echo "💎Installing ruby..."
install_asdf_language "ruby"
gem update --system
number_of_cores=$(sysctl -n hw.ncpu)A
bundle config --global jobs $((number_of_cores - 1))

fancy_echo "Installing node..."
bash "$HOME/.asdf/plugins/nodejs/bin/import-release-team-keyring"
install_asdf_language "nodejs"

fancy_echo "Done installinga asdf packages ✅"

# Setup Spacevim
fancy_echo "👽 Installing spacevim..."
curl -sLf \
  'https://spacevim.org/install.sh' | bash -s -- --install neovim
fancy_echo '👽 Spacevim setup successfully ✅'

# Setup dotfiles
fancy_echo '🗳Setting up dotfiles...'

git clone git://github.com/pauldariye/.dotfiles.git ~/dotfiles
env RCRC=$HOME/dotfiles/rcrc rcup
source ~/.config/fish/config.fish

# Setup Xcode
fancy_echo 'Installing Xcode CLI tools...'
xcode-select --install