#!/bin/bash
# This script is heavily adapted from Thoughtbot's awesome laptop setup script
# Source: https://github.com/thoughtbot/laptop/blob/master/mac

HOMEBREW_PREFIX="/opt/homebrew"

fancy_echo() {
  local fmt="$1"; shift
  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

fancy_echo "Starting up..."

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown - R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  fancy_echo '🍺 Installing brew...'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "✂️  Uninstalling old homebrew cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "🍻 Updating homebrew formulae..."
brew bundle dump --force


fancy_echo "🍻 Installing your packages from Brewfile..."

brew bundle --file=./Brewfile

fancy_echo "🍺 Brew was successfully installed ✅"

fancy_echo "🐠 Configuring fish as default shell..."

echo "$HOMEBREW_PREFIX/bin/fish" | sudo tee -a /etc/shells
chsh -s "$HOMEBREW_PREFIX/bin/fish"

fancy_echo "🐠 fish set as default shell"

fancy_echo "📦 Installing fisher and packages..."

set --local plugins (read --null ./config/fish/fishfile)
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher $plugins

fancy_echo "📦 fisher and packages installed"

# Setup Xcode
fancy_echo "Checking Xcode CLI tools..."

if ! command -v xcode-select -p; then
 fancy_echo 'Installing Xcode CLI tools...'
 xcode-select --install
fi

fancy_echo "Xcode CLI tools installed ✅"

fancy_echo "Your basic tools are all setup 🚀"
fancy_echo "follow the instructions in the README to complete the setup"

# a few things to add
# https://github.com/powerline/fonts
# https://github.com/jorgebucaran/fisher/issues/652#issue-788115513
# https://ghostty.org/docs/config -- config for theme, for font-family
